/** Icon app nhắn tin bịa (không dùng logo Messenger/iMessage thật) — base64
 *  literal tại author-time để tránh lỗi asset-encoding khi build. */
export const iconChat =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImciIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzM0RDM5OSIvPgogICAgPHN0b3Agb2Zmc2V0PSIxMDAlIiBzdG9wLWNvbG9yPSIjMEVBNUU5Ii8+CiAgPC9saW5lYXJHcmFkaWVudD48L2RlZnM+CiAgPHJlY3Qgd2lkdGg9IjEyOCIgaGVpZ2h0PSIxMjgiIHJ4PSIzMCIgZmlsbD0idXJsKCNnKSIvPgogIDxwYXRoIGQ9Ik0yOCA0MGg3MmExMCAxMCAwIDAgMSAxMCAxMHYzNGExMCAxMCAwIDAgMS0xMCAxMEg1NmwtMTggMTZ2LTE2SDI4YTEwIDEwIDAgMCAxLTEwLTEwVjUwYTEwIDEwIDAgMCAxIDEwLTEweiIgZmlsbD0iI2ZmZiIvPgo8L3N2Zz4=";
